name: Sync GitHub Issue to Jira

on:
  issues:
    types: [opened]

jobs:
  create-jira-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create Jira issue via API (Postman-style Auth)
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        run: |
          echo "Creating Jira issue for: ${{ github.event.issue.title }}"

          curl -X POST \
            -u "$JIRA_USER:$JIRA_TOKEN" \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            --data '{
              "fields": {
                "project": { "id": "10045" },
                "issuetype": { "id": "10010" },
                "summary": "'"${{ github.event.issue.title }}"'",
                "description": {
                  "type": "doc",
                  "version": 1,
                  "content": [
                    {
                      "type": "paragraph",
                      "content": [
                        {
                          "type": "text",
                          "text": "'"${{ github.event.issue.body }}"'"
                        }
                      ]
                    }
                  ]
                }
              }
            }' \
            https://vmhomelab.atlassian.net/rest/api/3/issue

          echo "Done ✅"
